{"uuid": "c6a8225b-3c34-4ff1-8f29-8d7b6cca706f", "children": ["20ddc51e-490e-45d2-b0f6-c372eea61c20", "300560f9-2232-424d-9b0f-c167ab6787b7", "4e1a9713-1582-4ac5-b9d1-7a2e4f36808f", "fc10386e-b2b9-4722-8fbd-d37bf217e560", "fc9d6fdf-f767-457c-a73d-921ecae06984", "8cf7054c-d66a-408a-8894-6306d5d58d7e"], "befores": [{"name": "xunit_setup_class_fixture_Test_apply", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_TIMED_OUT\n  (Session info: chrome=94.0.4606.81)\n\n", "trace": "  File \"D:\\Python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Python\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Python\\lib\\site-packages\\_pytest\\python.py\", line 811, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"D:\\Python\\lib\\site-packages\\_pytest\\python.py\", line 739, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\Program Files\\JetBrains\\PyCharm Community Edition 2020.2\\pytest_allure\\testcase\\test_apply.py\", line 19, in setup_class\n    cls.driver.get('http://sqwytst.wt.com:14352/')\n  File \"D:\\Python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"D:\\Python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1638603278178, "stop": 1638603322038}], "start": 1638603278178, "stop": 1638603322232}